### ISSUE TITLE
Fixed panel navigation (pipeline definition)

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-web#42]
An alternative approach to defining pipelines would be to "fix" the panels so the user would need to go through the required steps  (1. General options, 2. SQA criteria, 3. Actions) sequentially, **avoiding them to be selectable/clickable**. 

With this approach, in case that the user wants to go back (to check/modify an already provided value), this would be done through back/continue buttons (like the one we have now in the left menu).

@dianamariand92 
@gmolto

**Comment by gmolto** [comment]
I would keep the panel navigation in the left but to partially comply with your request, adding "Next" and "Back" buttons to the bottom of each panel. The rationale is that if the user wants to change something from the first panel while staying in the last one, it is much easier to directly go that panel using the panel in the left rather than flipping through the intermediate ones.

Currently, there are some checkins in place to avoid progressing through panels unless the required information is provided.

**Comment by dianamariand92** [comment]
I agree with Germán, I have included the back/next buttons in the forms.
